# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppem_normal <- function(y, x, z, d, pi, alpha_init, beta1_init, beta2_init, sigma_init, ninits, maxit, tol) {
    .Call(`_subgroupSLRT_cppem_normal`, y, x, z, d, pi, alpha_init, beta1_init, beta2_init, sigma_init, ninits, maxit, tol)
}

EM_gamma_fixed_cpp <- function(n, x, d, z, y, gamma, q1, theta_init, epsilon, maxit, xx, xy) {
    .Call(`_subgroupSLRT_EM_gamma_fixed_cpp`, n, x, d, z, y, gamma, q1, theta_init, epsilon, maxit, xx, xy)
}

llogit <- function(gamma, z, w) {
    .Call(`_subgroupSLRT_llogit`, gamma, z, w)
}

dlogit <- function(gamma, z, w) {
    .Call(`_subgroupSLRT_dlogit`, gamma, z, w)
}

obj <- function(gamma, z, x, y, alpha, beta, lambda, d, sigma) {
    .Call(`_subgroupSLRT_obj`, gamma, z, x, y, alpha, beta, lambda, d, sigma)
}

grad <- function(gamma, z, x, y, alpha, beta, lambda, d, sigma) {
    .Call(`_subgroupSLRT_grad`, gamma, z, x, y, alpha, beta, lambda, d, sigma)
}

